name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]


jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.x', '3.7', '3.x']
        django-version: ['1.11.29', '3.2.12']

    name: Python ${{ matrix.python-version }} / django ${{ matrix.django-version}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Setup deps
        run: python -m pip install django==${{ matrix.django-version }}

      - name: Run tests
        run: python -m unittest
